// ÖZMAKSAN — merkezi içerik verisi (çok sayfalı site + WXR üretimi için)

export const company = {
  legalName: "ÖZMAKSAN ISI SANAYİ VE TİCARET A.Ş.",
  brand: "ÖZMAKSAN",
  slogan: "YÜKSEK ISI TEKNOLOJİSİ",
  sloganEn: "HIGH HEATING TECHNOLOGY",
  founded: "1976",
  years: "49",
  address:
    "4. Organize Sanayi Bölgesi, 83404 Nolu Cadde No:10, Başpınar / Gaziantep / Türkiye",
  phones: ["+90 342 220 40 56", "+90 342 220 39 56", "+90 342 357 01 62"],
  fax: "+90 342 232 61 13",
  mobile: "+90 533 372 83 35",
  email: "ozmaksan@ozmaksan.com.tr",
  web: "ozmaksan.com.tr",
  social: {
    facebook: "https://www.facebook.com/OZMAKSANISI/",
    instagram: "https://www.instagram.com/ozmaksan_isi/",
    linkedin:
      "https://www.linkedin.com/in/ozmaksan-isi-san-tic-as-570399161",
    youtube: "https://www.youtube.com/@ozmaksan",
  },
};

// Ana menü (çok sayfalı)
export const nav = [
  { label: "Anasayfa", href: "index" },
  { label: "Kurumsal", href: "kurumsal" },
  { label: "Ürünler", href: "urunler" },
  { label: "Haberler", href: "haberler" },
  { label: "Referanslar", href: "referanslar" },
  { label: "Sertifikalar", href: "sertifikalar" },
  { label: "İletişim", href: "iletisim" },
];

export const categories = [
  { key: "buhar", label: "Buhar Kazanları", desc: "Skoç tip ve aküple ocaklı yüksek basınçlı buhar üretimi." },
  { key: "kizginsu", label: "Kızgın Su Kazanları", desc: "Yüksek sıcaklık ve basınçta kızgın su sistemleri." },
  { key: "sicaksu", label: "Sıcak Su Kazanları", desc: "Yoğuşmalı, sıvı/gaz ve katı yakıtlı merkezi ısıtma." },
  { key: "kizginyag", label: "Kızgın Yağ Kazanları", desc: "Proses ısıtma için 350°C'ye kadar termal yağ sistemleri." },
  { key: "enerji", label: "Enerji Geri Kazanım & Basınçlı Kaplar", desc: "Ekonomizer, atık ısı, tanklar ve basınçlı kaplar." },
];

export const products = [
  {
    slug: "steamax",
    name: "STEAmAX Boiler",
    series: "OSBK",
    category: "buhar",
    tagline: "Sıvı & gaz yakıtlı skoç tip yüksek basınçlı buhar kazanı",
    fuel: "Sıvı & Gaz",
    type: "Skoç Tip · 3 Geçişli",
    capacity: "600 – 24.000 kg/h buhar",
    pressure: "20 bar'a kadar",
    efficiency: "%90 – 92",
    image: "assets/products/steamax.jpg",
    pdf: "assets/catalogs/steamax.pdf",
    intro: [
      "OSBK serisi buhar kazanları uluslararası skoç tip olarak dizayn edilmiştir. Üretimin her safhası ve kalite kontrolü 97/23/EC ve EN-12953 normlarına uygundur.",
      "Üretimde yüksek kaliteli özel kazan sacı ile dikişsiz çelik çekme kazan borusu kullanılır. 24 ton/h buhar kapasitesine ve 20 bar çalışma basıncına kadar geniş bir ürün yelpazesine sahiptir.",
    ],
    features: [
      "3 geçişli uluslararası skoç tip tasarım",
      "Yüksek kaliteli özel kazan sacı ve dikişsiz borular",
      "Radyografik tarama ve hidrostatik test",
      "Opsiyonel ekonomizer & süperheater",
      "Düşük NOx'lu, kompakt ve yüksek verimli",
    ],
    specs: {
      columns: ["Model", "Kapasite (kg/h)"],
      rows: [
        ["OSBK-15", "600"], ["OSBK-30", "1.200"], ["OSBK-50", "2.000"],
        ["OSBK-75", "3.000"], ["OSBK-100", "4.000"], ["OSBK-150", "6.000"],
        ["OSBK-200", "8.000"], ["OSBK-300", "12.000"], ["OSBK-450", "18.000"],
        ["OSBK-600", "24.000"],
      ],
    },
  },
  {
    slug: "steampack",
    name: "STEAMpack Boiler",
    series: "Paket Ünite",
    category: "buhar",
    tagline: "Tak-çalıştır paket (skid) buhar sistemi",
    fuel: "Sıvı & Gaz",
    type: "Paket / Skid Ünite",
    capacity: "Talebe göre",
    pressure: "2014/68/EU uygun",
    efficiency: "Yüksek verim",
    image: "assets/products/steampack.jpg",
    pdf: "assets/catalogs/steampack.pdf",
    intro: [
      "STEAMpack paket buhar sistemleri; buhar kazanı ile birlikte pompa grubu, emniyet ekipmanları, kolektörler ve tüm yardımcı donanımların tek bir şase üzerine monte edildiği tak-çalıştır çözümlerdir.",
      "2014/68/EU basınçlı ekipman yönetmeliğine uygun üretilir; hızlı devreye alma ve kompakt yerleşim sağlar.",
    ],
    features: [
      "Komple paket (skid) çözüm",
      "Pompa grubu, emniyet ve kontrol ekipmanları dahil",
      "Hızlı devreye alma",
      "2014/68/EU yönetmeliğine uygun",
      "Minimum saha işçiliği, kompakt yerleşim",
    ],
  },
  {
    slug: "goldenmass",
    name: "GOLDENmass Boiler",
    series: "Aküple Ocaklı",
    category: "buhar",
    tagline: "Aküple ocaklı katı yakıtlı buhar kazanı",
    fuel: "Katı Yakıt (Kömür)",
    type: "Aküple / Ön Ocaklı",
    capacity: "Yüksek kapasiteli buhar",
    pressure: "Talebe göre",
    efficiency: "Yüksek verim",
    image: "assets/products/goldenmass.jpg",
    pdf: "assets/catalogs/goldenmass.pdf",
    intro: [
      "GOLDENmass serisi aküple (ön) ocaklı katı yakıtlı buhar kazanlarıdır. Kömür ve katı yakıtlarla yüksek kapasiteli, sürekli buhar üretimi için tasarlanmıştır.",
      "Ayrı yanma ocağı sayesinde yüksek verim ve kesintisiz buhar sağlar (örn. 2000 kg/h · 12 bar kömürlü buhar santrali).",
    ],
    features: [
      "Aküple (ön) yanma ocağı",
      "Katı yakıtla yüksek kapasiteli buhar",
      "Sürekli ve kararlı buhar üretimi",
      "Sağlam çelik gövde",
      "Endüstriyel proses için ideal",
    ],
  },
  {
    slug: "scotchsuper",
    name: "SCOTCHsuper Boiler",
    series: "OKSK",
    category: "kizginsu",
    tagline: "Sıvı & gaz yakıtlı skoç tip kızgın su kazanı",
    fuel: "Sıvı & Gaz",
    type: "Skoç Tip",
    capacity: "100.000 – 10.000.000 kcal/h",
    pressure: "24 bar'a kadar",
    efficiency: "%90 – 92",
    image: "assets/products/scotchsuper.jpg",
    pdf: "assets/catalogs/scotchsuper.pdf",
    intro: [
      "OKSK serisi sıvı ve gaz yakıtlı kızgın su kazanları uluslararası skoç tip olarak dizayn edilmiştir. 100.000 – 10.000.000 kcal/h gibi çok geniş bir kapasite aralığında üretilir.",
      "Geniş su hacmi ve optimum ısıl denge uzun ömür sağlar; uygun brülör seçimiyle düşük NOx'lu mükemmel yanma elde edilir.",
    ],
    features: [
      "Uluslararası skoç tip tasarım",
      "24 bar'a kadar çalışma basıncı",
      "10.000.000 kcal/h'e varan kapasite",
      "ST 35.8 dikişsiz kazan boruları (DIN 17175/2448)",
      "17Mn4 / 19Mn6 özel kazan sacı",
    ],
    specs: {
      columns: ["Model", "Kapasite (kcal/h)"],
      rows: [
        ["OKSK-100", "100.000"], ["OKSK-500", "500.000"], ["OKSK-1000", "1.000.000"],
        ["OKSK-2000", "2.000.000"], ["OKSK-3000", "3.000.000"], ["OKSK-5000", "5.000.000"],
        ["OKSK-7500", "7.500.000"], ["OKSK-10.000", "10.000.000"],
      ],
    },
  },
  {
    slug: "maxidens",
    name: "MAXIdens Boiler",
    series: "OYPK",
    category: "sicaksu",
    tagline: "Yoğuşmalı sıcak su kazanı — %109'a varan verim",
    fuel: "Doğalgaz / LPG / LNG",
    type: "Yoğuşmalı · 3 Geçişli",
    capacity: "86.000 – 860.000 kcal/h (100–1.000 kW)",
    pressure: "Merkezi ısıtma",
    efficiency: "%109'a kadar",
    image: "assets/products/maxidens.jpg",
    pdf: "assets/catalogs/maxidens.pdf",
    intro: [
      "OYPK serisi yoğuşmalı merkezi ısıtma kazanları doğalgaz, LPG ve LNG ile çalışır. 86.000 – 860.000 kcal/h (100–1.000 kW) kapasite aralığında üretilir.",
      "Türk Standartları Enstitüsü laboratuvarlarında gerçekleşen ısıl verim testleri sonucunda, verim değerleri %109,3'e varan oranlarda tescillenmiştir.",
    ],
    features: [
      "%109,3'e varan yüksek verim",
      "3 geçişli tasarım, paslanmaz çelik yoğuşma bölmesi",
      "80 mm alüminyum folyolu cam yünü izolasyon",
      "Düşük yakıt tüketimi, düşük emisyon",
      "2009/142/AT ve TS EN 15417 uygun · çevre dostu",
    ],
    specs: {
      columns: ["Model", "Kapasite (kcal/h)", "kW"],
      rows: [
        ["OYPK-100", "86.000", "100"], ["OYPK-150", "129.000", "150"],
        ["OYPK-200", "172.000", "200"], ["OYPK-300", "258.000", "300"],
        ["OYPK-400", "344.000", "400"], ["OYPK-500", "430.000", "500"],
        ["OYPK-700", "602.000", "700"], ["OYPK-800", "688.000", "800"],
        ["OYPK-1000", "860.000", "1.000"],
      ],
    },
  },
  {
    slug: "econox",
    name: "ECONOx Boiler",
    series: "OPK",
    category: "sicaksu",
    tagline: "Karşı basınçlı (reverse flame) sıcak su kazanı",
    fuel: "Sıvı & Gaz",
    type: "Reverse Flame / Karşı Basınçlı",
    capacity: "80.000 – 2.000.000 kcal/h (93–2.325 kW)",
    pressure: "Merkezi ısıtma",
    efficiency: "%90 – 92",
    image: "assets/products/econox.jpg",
    pdf: "assets/catalogs/econox.pdf",
    intro: [
      "OPK serisi sıvı ve gaz yakıtlı sıcak su kazanları 'Karşı Basınç' (Reverse Flame) teknolojisine göre üretilir. Brülör alevi ocak içinde geri döner; yanma gazlarının yarattığı karşı basınçla alev yön değiştirir.",
      "Bu sayede ısı transferi ve verim yükselir; 80.000 – 2.000.000 kcal/h aralığında üretilir.",
    ],
    features: [
      "Reverse Flame / karşı basınçlı teknoloji",
      "Yüksek ısı transferi ve verim",
      "1300°C'ye dayanıklı özel refrakter",
      "Düşük yakıt tüketimi",
      "Kompakt dizayn, kolay montaj",
    ],
    specs: {
      columns: ["Model", "Kapasite (kcal/h)", "kW"],
      rows: [
        ["OPK-80", "80.000", "93"], ["OPK-150", "150.000", "174"],
        ["OPK-300", "300.000", "349"], ["OPK-500", "500.000", "581"],
        ["OPK-700", "700.000", "814"], ["OPK-1000", "1.000.000", "1.163"],
        ["OPK-1500", "1.500.000", "1.744"], ["OPK-2000", "2.000.000", "2.325"],
      ],
    },
  },
  {
    slug: "scotchmax",
    name: "SCOTCHmax Boiler",
    series: "Skoç Tip",
    category: "sicaksu",
    tagline: "Sıvı & gaz yakıtlı skoç tip sıcak su kazanı",
    fuel: "Sıvı & Gaz",
    type: "Skoç Tip · 3 Geçişli",
    capacity: "Geniş kapasite aralığı",
    pressure: "Merkezi ısıtma",
    efficiency: "Yüksek verim",
    image: "assets/products/scotchmax.jpg",
    pdf: "assets/catalogs/scotchmax.pdf",
    intro: [
      "SCOTCHmax serisi sıvı ve gaz yakıtlı, uluslararası skoç tip 3 geçişli sıcak su kazanıdır. Üretimin her safhası 97/23/EEC PED, EN 303-5 ve TS 497 normlarına uygundur.",
      "Geniş su hacmi uzun ömür sağlar; düşük yakıt tüketimi ve yüksek ısı transferi sunar.",
    ],
    features: [
      "Skoç tip 3 geçişli tasarım",
      "Geniş su hacmi, uzun ömür",
      "Düşük yakıt tüketimi",
      "Dikişsiz kazan boruları",
      "Galvaniz kaplı, izoleli gövde",
    ],
  },
  {
    slug: "trinity",
    name: "TRInITY Boiler",
    series: "OUPK",
    category: "sicaksu",
    tagline: "Yeni nesil 3 geçişli sıvı & gaz yakıtlı sıcak su kazanı",
    fuel: "Sıvı & Gaz",
    type: "3 Geçişli",
    capacity: "90.000 – 1.200.000 kcal/h (105–1.395 kW)",
    pressure: "90/70 °C",
    efficiency: "Yüksek verim",
    image: "assets/products/trinity.jpg",
    pdf: "assets/catalogs/trinity.pdf",
    intro: [
      "TRINITY serisi sıvı ve gaz yakıtlı sıcak su kazanları üç geçişli dizayna sahip, Özmaksan'ın yeni nesil kazanlarındandır.",
      "Kazan gövdesinde optimum ısıl denge sağlanır; türbülatör kullanımıyla konveksiyonel ısı transferi artırılarak yüksek performans elde edilir.",
    ],
    features: [
      "Yeni nesil 3 geçişli tasarım",
      "Optimum ısıl denge",
      "Türbülatörlü yüksek verim",
      "80 mm alüminyum folyolu cam yünü izolasyon",
      "92/42/EEC, 2009/142/AT, TS 497 ve TS EN 303-304 uygun",
    ],
    specs: {
      columns: ["Model", "Kapasite (kcal/h)", "kW"],
      rows: [
        ["OUPK-90", "90.000", "105"], ["OUPK-150", "150.000", "174"],
        ["OUPK-200", "200.000", "233"], ["OUPK-300", "300.000", "349"],
        ["OUPK-500", "500.000", "581"], ["OUPK-700", "700.000", "814"],
        ["OUPK-900", "900.000", "1.047"], ["OUPK-1200", "1.200.000", "1.395"],
      ],
    },
  },
  {
    slug: "economass",
    name: "ECONOmass Boiler",
    series: "OKK",
    category: "sicaksu",
    tagline: "Elle yüklemeli katı yakıtlı sıcak su kazanı",
    fuel: "Katı Yakıt",
    type: "Skoç Tip · 3 Geçişli · Elle Yüklemeli",
    capacity: "100.000 – 1.000.000 kcal/h",
    pressure: "Merkezi ısıtma",
    efficiency: "%91'e kadar",
    image: "assets/products/economass.jpg",
    pdf: "assets/catalogs/economass.pdf",
    intro: [
      "OKK serisi elle yüklemeli katı yakıtlı sıcak su kazanları son Avrupa normlarına (EN 303-5) göre dizayn edilmiştir. Skoç tip üç geçişli yapıdadır.",
      "Geniş servis bunkeri, uzun ömür ve %91'e varan yüksek verim sunar; kömür, odun ve prina gibi katı yakıtlarla çalışır.",
    ],
    features: [
      "Elle yüklemeli, geniş yükleme bunkeri",
      "3 geçişli skoç tip",
      "%91'e varan verim",
      "1300°C refrakter malzeme",
      "Opsiyonel üfleme fanı ve kontrol paneli",
    ],
    specs: {
      columns: ["Model", "Kapasite (kcal/h)"],
      rows: [
        ["OKK-100", "100.000"], ["OKK-200", "200.000"], ["OKK-300", "300.000"],
        ["OKK-400", "400.000"], ["OKK-500", "500.000"], ["OKK-650", "650.000"],
        ["OKK-800", "800.000"], ["OKK-1000", "1.000.000"],
      ],
    },
  },
  {
    slug: "jumbomass",
    name: "JUMBOmass Boiler",
    series: "Elle Yüklemeli",
    category: "sicaksu",
    tagline: "Büyük kapasiteli elle yüklemeli katı yakıtlı kazan",
    fuel: "Katı Yakıt",
    type: "Elle Yüklemeli",
    capacity: "Geniş kapasite aralığı",
    pressure: "Merkezi ısıtma",
    efficiency: "Yüksek verim",
    image: "assets/products/jumbomass.jpg",
    pdf: "assets/catalogs/jumbomass.pdf",
    intro: [
      "JUMBOmass serisi elle yüklemeli katı yakıtlı sıcak su kazanları, EN direktiflerine uygun olarak büyük kapasiteli tesisler için üretilir.",
      "Geniş yanma hacmi ve kolay temizlenebilir tasarımıyla uzun ömürlü ve ekonomik çalışma sağlar.",
    ],
    features: [
      "Büyük kapasiteli, elle yüklemeli",
      "Geniş yanma hacmi",
      "EN direktiflerine uygun",
      "Dayanıklı gövde ve kolay kül temizliği",
      "Ekonomik katı yakıt kullanımı",
    ],
  },
  {
    slug: "automass",
    name: "AUTOmass Boiler",
    series: "OOPK",
    category: "sicaksu",
    tagline: "Otomatik (helezon) yüklemeli katı yakıtlı kazan",
    fuel: "Katı Yakıt (Otomatik)",
    type: "Otomatik Yüklemeli",
    capacity: "100.000 – 800.000 kcal/h",
    pressure: "Merkezi ısıtma",
    efficiency: "Yüksek verim",
    image: "assets/products/automass.jpg",
    pdf: "assets/catalogs/automass.pdf",
    intro: [
      "OOPK serisi otomatik yüklemeli katı yakıtlı sıcak su kazanları, katı yakıtı helezon vasıtasıyla otomatik besleme prensibiyle çalışır (EN 303-5).",
      "Prina, odun talaşı, fındık kömürü, odun peleti ve meyve kabuğu gibi yakıtlarla çalışabilir; düşük yakıt sarfiyatı sağlar. 100.000 – 800.000 kcal/h.",
    ],
    features: [
      "Otomatik helezon besleme sistemi",
      "Çoklu katı yakıt: prina, talaş, fındık kömürü, pelet, meyve kabuğu",
      "Düşük yakıt sarfiyatı",
      "Elektronik kontrol paneli",
      "Fan destekli verimli yanma",
    ],
    specs: {
      columns: ["Model", "Kapasite (kcal/h)"],
      rows: [
        ["OOPK-100", "100.000"], ["OOPK-200", "200.000"], ["OOPK-300", "300.000"],
        ["OOPK-400", "400.000"], ["OOPK-500", "500.000"], ["OOPK-600", "600.000"],
        ["OOPK-700", "700.000"], ["OOPK-800", "800.000"],
      ],
    },
  },
  {
    slug: "tempoil",
    name: "TEMPoIL Boiler",
    series: "KYK",
    category: "kizginyag",
    tagline: "Sıvı & gaz yakıtlı kızgın yağ (termal) kazanı",
    fuel: "Sıvı & Gaz",
    type: "Spiral Sarımlı",
    capacity: "500.000 – 5.000.000 kcal/h",
    pressure: "350 °C'ye kadar",
    efficiency: "%90 – 92",
    image: "assets/products/tempoil.jpg",
    pdf: "assets/catalogs/tempoil.pdf",
    intro: [
      "KYK serisi kızgın yağ kazanları sıvı ve gaz yakıtlı olup spiral sarımlı borulu dizayna sahiptir. Kızgın yağı serpantin borularda optimum hızda dolaştırarak 350°C'ye kadar kullanıma uygun ısı transferi sağlar.",
      "Tekstil, kimya, yağ, ağaç, gıda ve asfalt endüstrilerinde proses ısıtma için idealdir. 500.000 – 5.000.000 kcal/h.",
    ],
    features: [
      "Spiral sarımlı serpantin tasarım",
      "350°C'ye kadar çalışma sıcaklığı",
      "DIN 17155 kazan çeliği, DIN 17175/2448 spiral borular",
      "1300°C'ye dayanıklı refrakter",
      "100 mm kaya yünü izolasyon",
    ],
    usage: ["Tekstil", "Kimya", "Yağ Tesisleri", "Ağaç Endüstrisi", "Gıda", "Asfalt Plentleri", "İnşaat"],
    specs: {
      columns: ["Model", "Kapasite (kcal/h)", "Yağ Hacmi (Lt)"],
      rows: [
        ["KYK-500", "500.000", "240"], ["KYK-1000", "1.000.000", "600"],
        ["KYK-1500", "1.500.000", "850"], ["KYK-2000", "2.000.000", "1.200"],
        ["KYK-2500", "2.500.000", "1.750"], ["KYK-3000", "3.000.000", "2.000"],
        ["KYK-4000", "4.000.000", "2.900"], ["KYK-5000", "5.000.000", "3.900"],
      ],
    },
  },
  {
    slug: "oilmass",
    name: "OILmass Boiler",
    series: "KKYK",
    category: "kizginyag",
    tagline: "Katı yakıtlı (stokerli) kızgın yağ kazanı",
    fuel: "Katı Yakıt (Stokerli)",
    type: "Dikey Serpantin · Alttan Ocaklı",
    capacity: "500.000 – 3.000.000 kcal/h",
    pressure: "Proses ısıtma",
    efficiency: "Yüksek verim",
    image: "assets/products/oilmass.jpg",
    pdf: "assets/catalogs/oilmass.pdf",
    intro: [
      "KKYK serisi katı yakıtlı kızgın yağ kazanları, alttan ocaklı dikey serpantin sarımlı tasarımdır. Katı yakıt, helezon vasıtasıyla otomatik (stokerli) prensiple yüklenir.",
      "Prina, odun ve badem kabuğu gibi çeşitli katı yakıtlarla çalışır. 500.000 – 3.000.000 kcal/h.",
    ],
    features: [
      "Alttan ocaklı dikey serpantin tasarım",
      "Stokerli otomatik yükleme",
      "Çoklu katı yakıt kullanımı",
      "Kaya yünü izolasyon",
      "Opsiyonel komple paket ünite",
    ],
    specs: {
      columns: ["Model", "Kapasite (kcal/h)", "Yağ Hacmi (Lt)"],
      rows: [
        ["KKYK500", "500.000", "410"], ["KKYK1000", "1.000.000", "1.041"],
        ["KKYK1500", "1.500.000", "1.507"], ["KKYK2000", "2.000.000", "2.980"],
        ["KKYK2500", "2.500.000", "3.703"], ["KKYK3000", "3.000.000", "4.090"],
      ],
    },
  },
  {
    slug: "enerji-geri-kazanim",
    name: "Enerji Geri Kazanım & Basınçlı Kaplar",
    series: "Yardımcı Donanım",
    category: "enerji",
    tagline: "Ekonomizer, atık ısı, tanklar ve basınçlı kaplar",
    fuel: "—",
    type: "Basınçlı Kap / Ekipman",
    capacity: "Projeye özel",
    pressure: "AD 2000 / ASME",
    efficiency: "Yakıt tasarrufu",
    image: "assets/products/factory-boilers.jpg",
    pdf: "",
    intro: [
      "Kazan sistemlerini tamamlayan enerji geri kazanım ekipmanları ve basınçlı kaplar; baca gazı ısısını geri kazanarak yakıt tasarrufu ve yüksek sistem verimi sağlar.",
      "Tüm ekipmanlar AD 2000 Merkblatt ve ASME standartlarına uygun, yüksek makine mühendislerinden oluşan ekibimiz tarafından projeye özel tasarlanır.",
    ],
    features: [
      "Ekonomizer & Reküperatörler — baca gazından ısı geri kazanımı",
      "Atık Isı & Bioatık Kazanları — TÜBİTAK destekli AR-GE",
      "Akümülasyon Tankları — jeotermal ve buhar enerji depolama",
      "N-Pentan & Yakıt Depolama Tankları (yer üstü / yer altı)",
      "Degazör, Kondens Tankı, Flaş Buhar Tankı, Boyler",
      "Isı Eşanjörleri, Bacalar ve Kızdırıcı Üniteleri",
    ],
  },
];

export const auxiliaries = [
  "Degazörler", "Eşanjörler", "Ekonomizerler", "Reküperatörler",
  "Kondens Tankları", "Flaş Buhar Tankları", "Boylerler", "Bacalar",
  "Kızdırıcı Üniteleri", "Akümülasyon Tankları", "N-Pentan Depolama Tankları",
  "Yakıt Depolama Tankları",
];

export const certs = [
  { code: "CE", note: "Szutest — 2007'den beri" },
  { code: "ISO 9001", note: "TÜV — kalite yönetim sistemi" },
  { code: "TSE", note: "Onaylı endüstriyel kazanlar" },
  { code: "ASME", note: "Uluslararası basınçlı kap standardı" },
  { code: "AD 2000", note: "Merkblatt standartları" },
  { code: "TÜV", note: "Bağımsız gözetim ve test" },
  { code: "EPDK", note: "Doğalgaz dönüşüm sertifikası" },
  { code: "TÜRK LOYDU", note: "Sertifikalı üretim" },
  { code: "K.B.S.B.", note: "Kazan ve Basınçlı Kap San. Birliği" },
  { code: "SZUTEST", note: "Onaylanmış kuruluş" },
  { code: "DIN", note: "Alman malzeme normları" },
  { code: "TURSEFF", note: "Verimli teknoloji referansı" },
];

export const sectors = [
  "Tekstil & İplik", "Kimya & Petrokimya", "İlaç Sanayi", "Gıda & İçecek",
  "Kağıt & Ambalaj", "Metal & Cam", "Otel & AVM", "Hastane & Sterilizasyon",
  "Seracılık & Besicilik", "Jeotermal Enerji", "Asfalt & İnşaat", "Kamu Kurumları",
  "Endüstriyel Çamaşırhane", "Boyama & Dokuma", "Mobilya & Ağaç", "Petrol & Rafineri",
];

export const references = [
  "Mercedes-Benz", "Coca-Cola", "PepsiCo Beverages", "KIA Motors", "Aygaz",
  "Abdi İbrahim", "Penti", "Oba Makarna", "Saka Holding", "Ferrero Türkiye",
  "Kara Holding", "Fargona Yog-Moy", "Mutlu Makarna", "KÇS Gazbeton", "Altaş Grup",
  "Bondoll", "MIFCO", "EGPI", "Sanko Enerji", "Uzkabel", "Akça Enerji",
  "Assan Alüminyum", "Kayalı Enerji", "Reckitt Benckiser", "Sis Enerji", "Emirates",
  "Koruma Klor", "Dedeman Hotel", "Limak", "Reha Süt", "Weatherford", "Sibline",
  "Kalyon Stadyum", "Aves A.Ş.", "Multi Development", "Asia", "Maitex", "BOTAŞ",
  "Türkiye Petrolleri (TPAO)", "Nuh Çimento", "İSDEMİR", "JUB Group", "Mogul Tekstil",
  "Menderes Geothermal", "Kadooğlu Yağ", "Greeneco Enerji", "Universal Hastanesi",
  "Acarsan Gıda", "Altunsa", "Lidersan Sağlık", "Kassatly Chtaura", "Enviro Energia",
  "Mado", "SCLI Baghdad", "Chtoora", "Hawa Chicken", "TOKİ", "Erdemir",
];

export const faq = [
  {
    q: "Hangi standartlara uygun üretim yapıyorsunuz?",
    a: "97/23/EC (PED), 2014/68/EU, EN 12953, EN 303-5, AD 2000 Merkblatt, ASME, TSE ve CE standartlarına uygun üretim yapılmaktadır. Basınç ve güvenlik testleri bağımsız kuruluş gözetiminde gerçekleştirilir.",
  },
  {
    q: "Montaj ve devreye alma hizmeti veriyor musunuz?",
    a: "Evet. Endüstriyel sistemlerin montajı ve devreye alınması konusunda uzman ekibimizle hizmet vermekteyiz. EPDK sertifikalı doğalgaz dönüşüm hizmeti de sunulmaktadır.",
  },
  {
    q: "Hangi yakıt türleriyle çalışan kazanlarınız var?",
    a: "Doğalgaz, LPG, LNG, sıvı yakıt ve katı yakıt (kömür, prina, odun talaşı, pelet, meyve kabuğu) ile çalışan geniş bir ürün yelpazemiz bulunmaktadır. Ayrıca çift yakıtlı (dual) çözümler sunulur.",
  },
  {
    q: "İhracat yapıyor musunuz?",
    a: "Evet. Ortadoğu, Kuzey Afrika ve Orta Asya başta olmak üzere birçok ülkeye doğrudan ihracat yapmaktayız. Üretimimizin yaklaşık %40'ı yurt dışı pazarlarına yöneliktir.",
  },
];

export const about = {
  intro: [
    "ÖZMAKSAN, 1976 yılında ısıtma ve buhar sektöründe hizmet vermek üzere Gaziantep'e kurulmuş olup, uzun yıllardır basınçlı kaplar üretim sektöründe faaliyet göstermektedir.",
    "17.000 m² üretim tesisimizde yüksek basınçlı buhar kazanları, kızgın su ve kızgın yağ kazanları, atık ısı kazanları, buhar jeneratörleri, ısı eşanjörleri, ekonomizerler, akümülasyon tankları ve enerji geri kazanım ekipmanları üretmekteyiz.",
    "Güneydoğu Anadolu bölgesinin en geniş üretim kapasitesine sahip firmalarından biri olarak, modern üretim altyapısı ve uzman mühendis kadrosuyla yurt içi ve yurt dışında önde gelen sanayi kuruluşlarının tedarikçisiyiz.",
  ],
  stats: [
    { value: "49", suffix: "", label: "Yıllık Tecrübe" },
    { value: "17000", suffix: "", label: "m² Üretim Alanı" },
    { value: "3000", suffix: "", label: "Ton/Yıl Kapasite" },
    { value: "40", prefix: "%", suffix: "", label: "İhracat Oranı" },
  ],
};

export const exportCountries = [
  "Irak", "Mısır", "Libya", "Lübnan", "Ürdün", "Birleşik Arap Emirlikleri",
  "Tunus", "Cezayir", "Fas", "Moldova", "Güney Afrika", "Azerbaycan",
  "Gürcistan", "Türkmenistan", "Kazakistan", "Özbekistan",
  "Kuzey Kıbrıs Türk Cumhuriyeti", "Yunanistan", "Pakistan",
];

export const featuredProducts = ["steamax", "maxidens", "scotchsuper", "tempoil", "automass", "econox"];

export const corporate = {
  vision: "Yüksek basınçlı buhar ve ısı teknolojilerinde uluslararası ölçekte tanınan, yenilikçi ve güvenilir bir dünya markası olmak; enerji verimliliği ve sürdürülebilir üretimde sektöre yön vermek.",
  mission: "1976'dan bu yana edindiğimiz mühendislik birikimiyle; müşterilerimizin ihtiyaçlarına uygun, uluslararası standartlarda, güvenli ve verimli basınçlı kap ve kazan çözümleri üretmek, satış sonrası destekle uzun ömürlü iş ortaklıkları kurmak.",
  companies: "ÖZMAKSAN Isı Sanayi Tic. A.Ş. çatısı altında; basınçlı kap ve kazan üretimi, enerji geri kazanım sistemleri ve anahtar teslim kazan dairesi kurulumu alanlarında faaliyet gösteren üretim ve mühendislik birimlerimizle hizmet veriyoruz.",
};
